version: "3.7"

services:
    web:
        # image: node:16-alpine
        image: node:16.13.0-alpine3.14
        command: sh -c "apk add --no-cache git && yarn install && tail -F anything"
        # command: tail -F anything
        # command: sh -c "npm install && npm start"
        # command: sh -c "npm install && tail -F anything"
        # command: sh -c "tail -F anything"
        # command: /bin/sh -c "while sleep 1000; do :; done"
        ports:
            - 9000:9000
        working_dir: /app
        volumes:
            - ./:/app
