version: "3.7"

services:
    web:
        # image: node:16-alpine
        image: node:latest
        # command: sh -c "yarn install"
        command: tail -F anything
        # command: sh -c "npm install && npm start"
        # command: sh -c "npm install && tail -F anything"
        # command: sh -c "tail -F anything"
        # command: /bin/sh -c "while sleep 1000; do :; done"
        ports:
            - 9000:9000
        working_dir: /app
        volumes:
            - ./:/app
